### ISSUE TITLE
Any way to remember the notes I created when I reopen the window?

### ISSUE THREAD

**Issue by stiliyan** [boardPro43119/sticky-notes#2]
This is a really helpful app! However, the notes I create disappear any time I close my browser... and when I reopen it I get the same 7 notes, which I have to delete and then recreate my own. 

Is there a way to make it remember my notes and show them to me when I come back?

**Comment by stiliyan** [comment]
Here's a suggested approach for now :)
1. Create a `package.json` file:
    name, version, description, dependencies, requiring express, socket.io, http, redis
1. install modules with `npm install`
2. create a node server application file and require modules
3. Initialize an express app, and point it to the public directory
4. Create a root route that serves the html code to the client
5. Link the html code with the javascript and CSS in the public directory
6. Listen on port 3000

**Comment by boardPro43119** [comment]
Thank you, I have just made a new commit with these changes made.  Saving the notes so you can access them when you reopen your browser will come soon.

**Comment by boardPro43119** [comment]
In my latest commit, I have created a Redis list `notes` where the notes will be stored upon creation, and put the code that adds a note to the page inside of an `addNote()` function.  My next step is to have these notes added to the page upon refreshing or reopening it.  Here are the steps I will take to do this:
1. Upon connection to the server, for each element in the `notes` list, emit a new event to the client passing in the note's title, content, and color
2. Upon this new event being emitted, on the client call the `addNote()` function with paramaters equal to the arguments passed into to the event emitter
